#!/bin/bash


for value in {1..20}
do
	echo Testing num-workers: $value
	python3 main.py --env-name PendulumTheta-v0 --num-workers $value --fast-lr 0.1 --max-kl 0.01 --fast-batch-size 20 --meta-batch-size 40 --num-layers 2 --hidden-size 100 --num-batches 100 --gamma 0.99 --tau 1.0 --cg-damping 1e-5 --ls-max-steps 15 --output-folder pendulum-dir-num-workers-$value --device cuda
done

echo ALL DONE!
